server:
  port: 9061

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway


spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: PERSONNEL-DEPARTMENT-SERVICE
          uri: lb://PERSONNEL-DEPARTMENT-SERVICE
          predicates:
            - Path=/personnel-department/**
        - id: HALL-SERVICE
          uri: lb://HALL-SERVICE
          predicates:
            - Path=/hall/**
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/Restaurant
            token-uri: http://localhost:8080/auth/realms/Restaurant/protocol/openid-connect/token
            authorization-uri: http://localhost:8080/auth/realms/Restaurant/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8080/auth/realms/Restaurant/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          api-gateway-client:
            client-name: personnel-auth
            provider: keycloak
            client-id: gateway-client
            client-secret: b28a8ff6-d867-44af-a01d-d802b5533da7
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:9061/login/oauth2/code/keycloak"

  application:
    name: API-GATEWAY


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost