server:
  port: 9061

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway


spring:
  cloud:
    gateway:
      routes:
        - id: PERSONNEL-DEPARTMENT-SERVICE
          uri: lb://PERSONNEL-DEPARTMENT-SERVICE
          predicates:
            - Path=/personnel-department/**
        - id: HALL-SERVICE
          uri: lb://HALL-SERVICE
          predicates:
            - Path=/hall/**

  application:
    name: API-GATEWAY

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost